name: OpenWrt-CI

on:
  workflow_dispatch:
    inputs:
      config_path:
        description: 'Path to your .config file'
        required: true
        default: '.config'

permissions:
  contents: read

jobs:
  build_openwrt:
    name: Build OpenWrt with Custom Config
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout OpenWrt
        uses: actions/checkout@v4
        with:
          path: openwrt

      - name: Copy custom config file
        run: |
          cp ${{ github.event.inputs.config_path }} openwrt/.config
          
      - name: Update feeds
        working-directory: openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Download packages
        working-directory: openwrt
        run: make download -j$(nproc)

      - name: Compile firmware
        working-directory: openwrt
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "Compilation finished"
          du -h --max-depth=1 ./bin

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_firmware
          path: openwrt/bin/targets/
