name: OpenWrt Auto-Release

on:
  workflow_dispatch:
    inputs:
      version_base:
        description: 'Base version number (e.g., 1.0)'
        required: false
        default: '1.0'

permissions:
  contents: write

jobs:
  build_and_release:
    name: Build and Release OpenWrt
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 需要获取完整历史记录来计算版本号

      - name: Verify .config exists
        run: |
          if [ ! -f ".config" ]; then
            echo "::error::.config file not found in repository root"
            ls -la
            exit 1
          fi
          echo ".config file found and will be used"

      - name: Calculate next version number
        id: version
        run: |
          BASE_VERSION=${{ github.event.inputs.version_base }}
          BUILD_DATE=$(date +'%Y%m%d')
          BUILD_COUNT=$(git tag -l "v${BASE_VERSION}-${BUILD_DATE}*" | wc -l)
          NEXT_COUNT=$((BUILD_COUNT + 1))
          FULL_VERSION="v${BASE_VERSION}-${BUILD_DATE}-${NEXT_COUNT}"
          echo "version=${FULL_VERSION}" >> $GITHUB_OUTPUT
          echo "Next version: ${FULL_VERSION}"

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Download packages
        run: make download -j$(nproc)

      - name: Compile firmware
        run: make -j$(nproc) || make -j1 V=s

      - name: Find firmware files
        id: find-firmware
        run: |
          FIRMWARE_PATH=$(find bin/targets/ -type f \( -name "*.bin" -o -name "*.img" -o -name "*.gz" \))
          echo "firmware_path=${FIRMWARE_PATH}" >> $GITHUB_OUTPUT
          echo "Found firmware: ${FIRMWARE_PATH}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: OpenWrt ${{ steps.version.outputs.version }}
          body: |
            ### 自动构建的 OpenWrt 固件
            
            **版本**: ${{ steps.version.outputs.version }}
            **构建日期**: $(date -u +'%Y-%m-%d %H:%M:%S UTC')
            
            包含以下固件文件:
            ${{ steps.find-firmware.outputs.firmware_path }}
          files: ${{ steps.find-firmware.outputs.firmware_path }}
          draft: false
          prerelease: false
